// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBbto8M76DjiKT7mUaMHeOErw4_5L6dLJs',
    appId: '1:291481355943:web:38280ffbd5ea7f6c587d82',
    messagingSenderId: '291481355943',
    projectId: 'project-aplikasi-gizi',
    authDomain: 'project-aplikasi-gizi.firebaseapp.com',
    storageBucket: 'project-aplikasi-gizi.firebasestorage.app',
    measurementId: 'G-D0LFN1XKCG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDGZ0dhJlexQx9LktQjFNpo7UATppPcHbs',
    appId: '1:291481355943:android:c9c76723b6015640587d82',
    messagingSenderId: '291481355943',
    projectId: 'project-aplikasi-gizi',
    storageBucket: 'project-aplikasi-gizi.firebasestorage.app',
  );
}
