// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBbto8M76DjiKT7mUaMHeOErw4_5L6dLJs',
    appId: '1:291481355943:web:38280ffbd5ea7f6c587d82',
    messagingSenderId: '291481355943',
    projectId: 'project-aplikasi-gizi',
    authDomain: 'project-aplikasi-gizi.firebaseapp.com',
    storageBucket: 'project-aplikasi-gizi.firebasestorage.app',
    measurementId: 'G-D0LFN1XKCG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDGZ0dhJlexQx9LktQjFNpo7UATppPcHbs',
    appId: '1:291481355943:android:c9c76723b6015640587d82',
    messagingSenderId: '291481355943',
    projectId: 'project-aplikasi-gizi',
    storageBucket: 'project-aplikasi-gizi.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBIIAxWHg6hp4Y3nx2s4firTIkW7KUJIIc',
    appId: '1:291481355943:ios:7e8c1fc38fa4f4fe587d82',
    messagingSenderId: '291481355943',
    projectId: 'project-aplikasi-gizi',
    storageBucket: 'project-aplikasi-gizi.firebasestorage.app',
    androidClientId: '291481355943-aum3neeg3ju50tdckvdb5lu7dvl1dcq2.apps.googleusercontent.com',
    iosClientId: '291481355943-r7nb9n7ll0knp8spv6f7jir2rhimilv0.apps.googleusercontent.com',
    iosBundleId: 'com.example.aplikasiDiagnosaGizi',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBIIAxWHg6hp4Y3nx2s4firTIkW7KUJIIc',
    appId: '1:291481355943:ios:7e8c1fc38fa4f4fe587d82',
    messagingSenderId: '291481355943',
    projectId: 'project-aplikasi-gizi',
    storageBucket: 'project-aplikasi-gizi.firebasestorage.app',
    androidClientId: '291481355943-aum3neeg3ju50tdckvdb5lu7dvl1dcq2.apps.googleusercontent.com',
    iosClientId: '291481355943-r7nb9n7ll0knp8spv6f7jir2rhimilv0.apps.googleusercontent.com',
    iosBundleId: 'com.example.aplikasiDiagnosaGizi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBbto8M76DjiKT7mUaMHeOErw4_5L6dLJs',
    appId: '1:291481355943:web:44f207b29368636b587d82',
    messagingSenderId: '291481355943',
    projectId: 'project-aplikasi-gizi',
    authDomain: 'project-aplikasi-gizi.firebaseapp.com',
    storageBucket: 'project-aplikasi-gizi.firebasestorage.app',
    measurementId: 'G-8284DLQ37W',
  );

}